# Generated by Django 5.2.14 on 2026-05-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employ",
            old_name="phone_no",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="employ",
            old_name="profile_img",
            new_name="profile_image",
        ),
    ]
