# Generated by Django 5.2.14 on 2026-05-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encodin_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employ",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.employee",
                    ),
                ),
            ],
        ),
    ]
